# Generated by Django 5.1.3 on 2024-11-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='decim',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
